# fly.toml app configuration file generated for tasteranker on 2024-09-08T14:19:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tasteranker'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.22.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "migrate -database \"${DATABASE_URL}\" -path /app/migrations up"
  strategy = "rolling"
