// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main><p>The goal is to rate restaurants by comparison.</p><article><h2>Ratings</h2><p>People typically don't use the full range of scores when they leave reviews. It's normal to only leave a review when you feel strongly, because you had an experience that was abnormally positive or negative.</p><p>We might get a better picture of the typical experience by making random comparisons betwen restaurants.</p><p>Getting people to compare restaurants rather than review them individually allows us to calculate an Elo-type rating similar to those used to rank chess players.</p></article><article><h2>Analysis</h2><p>This kind of rating system also allows for detailed analysis that can produce recommendations based on user profiles. People with similar combinations of preferences have similar taste. If we collect some information about the users, we may be able to filter the comparisons and use a smaller subset to produce ratings: We could identify the best Italian restaurant in London as rated by Italians. </p><p>Comparison data could also be filtered by time to show trends or recent performance.</p></article></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
