# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Upload assets to Fly Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: auto
        run: aws s3 sync ./assets s3://frosty-sound-5710/assets --delete --endpoint-url https://fly.storage.tigris.dev

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Debug DATABASE_URL
        run: echo "DATABASE_URL=${DATABASE_URL:0:5}... (masked)"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL:0:5 }}

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
